apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc }}
  database: {{ .Values.mysql.database | b64enc }}
  user: {{ .Values.mysql.user | b64enc }}
  password: {{ .Values.mysql.password | b64enc }}