services: 
  web:
    image: ${DOCKERHUB_USER}/spacecapybara_app:${VERSION} # Match the GitHub Actions tag
    container_name: spacecapybara_web
    ports: 
      - "${WEB_PORT}:${WEB_PORT}" 
    volumes: 
      - .:/app 
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - WEB_PORT=${WEB_PORT} 
      - DOCKERHUB_USER=${DOCKERHUB_USER}  
      - VERSION=${VERSION} 
    depends_on:
      - db

  # running a mysql container 
  db: 
    image: mysql:8.0  #pulling an existing image from dockerhub/local
    container_name: mysql_container 
    restart: always # if the container stops/crashes/etc., always restart it
    environment: # environment variables required for a myswl database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${SQL_PORT}:3306"
    volumes: # mounting the db's data dir inside the container, to an outside volume
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro # Mount the init.sql file


# an outside volume to store the db's data in
volumes:
  db_data: